# Generated by Django 4.2.7 on 2026-02-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GoMyanmar', max_length=100)),
                ('site_description', models.TextField(default="Myanmar's Premier Travel Planning Platform")),
                ('default_currency', models.CharField(default='MMK - Myanmar Kyat', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('email_address', models.EmailField(default='noreply@gomyanmar.com', max_length=254)),
                ('email_password', models.CharField(blank=True, max_length=255)),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
