# Generated by Django 4.2.7 on 2026-03-06 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', 'XXXX_alter_hotel_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Price in MMK (Myanmar Kyat)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
