# Generated by Django 4.2.7 on 2026-03-06 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_alter_hotel_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='custom_itinerary',
            field=models.JSONField(blank=True, default=dict, help_text='Custom itinerary with selected attractions'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Price in MMK (Myanmar Kyat)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
