# Generated by Django 4.2.7 on 2026-03-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_tripplan_custom_itinerary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='selected_attractions_data',
            field=models.JSONField(blank=True, default=list, help_text='List of selected attractions with coordinates'),
        ),
    ]
