# Generated by Django 4.2.7 on 2026-03-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_tripplan_selected_attractions_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trip Plan', 'verbose_name_plural': 'Trip Plans'},
        ),
        migrations.AddField(
            model_name='room',
            name='extra_bed_available',
            field=models.BooleanField(default=False, help_text='Whether this room can accommodate an extra bed'),
        ),
        migrations.AddField(
            model_name='room',
            name='extra_bed_cost',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Cost for extra bed per night in MMK', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='max_extra_beds',
            field=models.IntegerField(default=0, help_text='Maximum number of extra beds allowed in this room'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='extra_beds',
            field=models.IntegerField(default=0, help_text='Number of extra beds booked for this room'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='extra_beds_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total cost for extra beds', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='selected_rooms',
            field=models.JSONField(blank=True, default=dict, help_text='Selected rooms with details including extra beds'),
        ),
        migrations.AddIndex(
            model_name='tripplan',
            index=models.Index(fields=['user', '-created_at'], name='planner_tri_user_id_27760a_idx'),
        ),
        migrations.AddIndex(
            model_name='tripplan',
            index=models.Index(fields=['status'], name='planner_tri_status_bedee5_idx'),
        ),
        migrations.AddIndex(
            model_name='tripplan',
            index=models.Index(fields=['start_date'], name='planner_tri_start_d_7152a8_idx'),
        ),
    ]
