# Generated by Django 4.2.7 on 2026-01-15 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_bookedseat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedseat',
            options={'ordering': ['transport_type', 'transport_id', 'schedule_date', 'seat_number']},
        ),
        migrations.AlterUniqueTogether(
            name='bookedseat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookedseat',
            name='schedule_date',
            field=models.DateField(default=datetime.date(2026, 1, 15)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookedseat',
            unique_together={('transport_type', 'transport_id', 'schedule_date', 'seat_number')},
        ),
        migrations.CreateModel(
            name='TransportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('flight', 'Flight'), ('bus', 'Bus'), ('car', 'Car')], max_length=10)),
                ('transport_id', models.IntegerField()),
                ('travel_date', models.DateField()),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=0, help_text='Price in MMK', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['travel_date', 'departure_time'],
                'indexes': [models.Index(fields=['transport_type', 'travel_date'], name='planner_tra_transpo_b20eae_idx'), models.Index(fields=['travel_date', 'is_active'], name='planner_tra_travel__ea7f3c_idx')],
                'unique_together': {('transport_type', 'transport_id', 'travel_date')},
            },
        ),
    ]
