# Generated by Django 4.2.7 on 2026-01-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_bookedseat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(default=list, help_text="List of amenities (e.g., ['wifi', 'pool', 'spa'])"),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('budget', 'Budget (Under 50,000 MMK)'), ('medium', 'Medium (50,000 - 150,000 MMK)'), ('luxury', 'Luxury (150,000+ MMK)'), ('high', 'High-End (Premium Luxury)')], default='medium', max_length=20),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['destination', 'category'], name='planner_hot_destina_f30531_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_active'], name='planner_hot_is_acti_a36a60_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['price_per_night'], name='planner_hot_price_p_d67ba8_idx'),
        ),
    ]
