# Generated by Django 4.2.7 on 2026-02-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_hotel_options_hotel_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='attractions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='cultural_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image1',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image2',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image3',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image4',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='local_cuisine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='tips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
