# Generated by Django 4.2.7 on 2026-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_destination_activities_destination_attractions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
