# Generated by Django 4.2.7 on 2026-02-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_alter_hotel_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='selected_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
