# Generated by Django 4.2.7 on 2026-02-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_tripplan_selected_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_region',
            field=models.BooleanField(default=False, help_text='Is this a region/city (True) or a specific place/attraction (False)?'),
        ),
        migrations.AddField(
            model_name='destination',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent region/city that contains this place', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='planner.destination'),
        ),
    ]
