# Generated by Django 4.2.7 on 2026-03-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_destination_is_region_destination_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='gallery_captions',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object storing captions for gallery images'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image5',
            field=models.ImageField(blank=True, help_text='Gallery photo 5 for attractions', null=True, upload_to='destinations/gallery/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image6',
            field=models.ImageField(blank=True, help_text='Gallery photo 6 for attractions', null=True, upload_to='destinations/gallery/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image7',
            field=models.ImageField(blank=True, help_text='Gallery photo 7 for attractions', null=True, upload_to='destinations/gallery/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_image8',
            field=models.ImageField(blank=True, help_text='Gallery photo 8 for attractions', null=True, upload_to='destinations/gallery/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_image1',
            field=models.ImageField(blank=True, help_text='Gallery photo 1 for attractions', null=True, upload_to='destinations/gallery/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_image2',
            field=models.ImageField(blank=True, help_text='Gallery photo 2 for attractions', null=True, upload_to='destinations/gallery/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_image3',
            field=models.ImageField(blank=True, help_text='Gallery photo 3 for attractions', null=True, upload_to='destinations/gallery/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='gallery_image4',
            field=models.ImageField(blank=True, help_text='Gallery photo 4 for attractions', null=True, upload_to='destinations/gallery/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Main profile photo for city/town', null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Alternative main image field', null=True, upload_to='destinations/'),
        ),
    ]
