# Generated by Django 4.2.7 on 2026-03-03 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0015_destination_gallery_captions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_occupancy', models.IntegerField(default=2)),
                ('base_price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.IntegerField(default=1)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=0, help_text='Override hotel price per night for this room', max_digits=10, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('needs_maintenance', models.BooleanField(default=False)),
                ('bed_type', models.CharField(blank=True, max_length=50)),
                ('has_window', models.BooleanField(default=True)),
                ('has_balcony', models.BooleanField(default=False)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='planner.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='planner.roomtype')),
            ],
            options={
                'ordering': ['hotel', 'room_number'],
                'unique_together': {('hotel', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guests', models.IntegerField(default=1)),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('temporary', 'Temporary (Not Confirmed)'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='temporary', max_length=20)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='planner.room')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='planner.tripplan')),
            ],
            options={
                'ordering': ['-booking_time'],
                'indexes': [models.Index(fields=['room', 'check_in_date', 'check_out_date'], name='planner_roo_room_id_9fea04_idx'), models.Index(fields=['status'], name='planner_roo_status_63ef9f_idx')],
            },
        ),
    ]
