# Generated by Django 6.0.2 on 2026-03-04 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_destination_gallery_captions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='attractions',
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='planner.destination')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['destination'], name='planner_att_destina_b229fd_idx'), models.Index(fields=['name'], name='planner_att_name_a2ba67_idx')],
                'unique_together': {('destination', 'name')},
            },
        ),
    ]
