# Generated by Django 6.0.2 on 2026-03-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_remove_destination_attractions_attraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('time', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('icon', models.CharField(default='fas fa-star', max_length=100)),
                ('is_custom', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planner.tripplan')),
            ],
            options={
                'ordering': ['trip', 'day_number', 'time', 'id'],
                'indexes': [models.Index(fields=['trip', 'day_number'], name='planner_tri_trip_id_059d0f_idx')],
            },
        ),
    ]
