# Generated by Django 4.2.7 on 2026-03-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_roomtype_room_roombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='selected_rooms',
            field=models.JSONField(blank=True, default=dict, help_text='Selected rooms with details'),
        ),
    ]
