# Generated by Django 4.2.7 on 2026-03-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_tripplan_selected_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['room', 'date'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'is_active'], name='planner_roo_hotel_i_e17a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='planner_roo_room_ty_6644af_idx'),
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='planner.room'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['date', 'is_available'], name='planner_roo_date_141a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['room', 'date'], name='planner_roo_room_id_c3edf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomavailability',
            unique_together={('room', 'date')},
        ),
    ]
